var nome = prompt("Digite o nome da sua escola")
var nome2 = prompt("Digite o nome de um aluno da sua escola")
var matricula = prompt("Digite a sua matricula da escola")
var curso = prompt("Digite o seu curso da escola")
var semestre = prompt("Digite o seu semestre da escola")
var unidadeCurricular = prompt("Digite a sua unidade curricular")

document.write("Nome da escola: " + nome)
document.write("<br>")
document.write("Nome do aluno: " + nome2)
document.write("<br>")
document.write("Matricula: " + matricula)
document.write("<br>")
document.write("Curso: " + curso)
document.write("<br>")
document.write("Semestre: " + semestre)
document.write("<br>")
document.write("Unidade curricular: " + unidadeCurricular)